### ISSUE TITLE
Verify URL with UI

### ISSUE THREAD

**Issue by dhawton** [nzvirtual/org.flyak.api#13]
https://github.com/FlyAKOrg/org.flyak.api/blob/d68ef4d647b56faef6bb87ab92790b148050e21f/src/main/resources/application.properties#L6

This along with a not-yet coded Forgotten Password path need to be handled by the front end.  Coordinate pathings and adjust the application.properties file.

**Comment by rahulp959** [comment]
Frontend URL:
Verification
${frontendUrl}/verify/:token

Forgot Password:
${frontendUrl}/forgot-password/:token
